### ISSUE TITLE
Error on Cypress

### ISSUE THREAD

**Issue by andrewkrug** [Denis1990/sshxblock#9]
When attempting a save in course studio to an xblock the following error is generated making this unusable.

  File "/opt/bitnami/apps/edx/edx-platform/common/lib/xmodule/xmodule/modulestore/mongo/base.py", line 138, in set
    (Scope.children, Scope.settings, Scope.content),
InvalidScopeError: Invalid scope: Key(scope=ScopeBase(user=UserScope.ONE, block=BlockScope.USAGE, name=u'user_state'), user_id=None, block_scope_id=BlockUsageLocator(CourseLocator(u'edX', u'DemoX', u'Demo_Course', None, None), u'ssh', u'7f64c7cc1d9646e2af4236dca7498d7e'), field_name='ssh_hostnames', block_family='xblock.v1'). Valid scopes are: (Scope.children, ScopeBase(user=UserScope.NONE, block=BlockScope.USAGE, name=u'settings'), ScopeBase(user=UserScope.NONE, block=BlockScope.DEFINITION, name=u'content'))

**Comment by mirobillis** [comment]
The error was found and will be fixed with the next commit as soon as i get the chance to make some tests first!

If for some reason you can't wait the commit or it is delayed,you can change mannualy the lines 21-28 from file ssh.py
where scope=Scope.user_state replace with scope=Scope.settings

Let me know if it works for you.

I apologize for any inconvenience!

**Comment by mirobillis** [comment]
Ok i found the solution based on this
http://edx.readthedocs.org/projects/xblock-tutorial/en/latest/concepts/fields.html

Lines 21-28 should look like this 

ssh_host = String(default='', scope=Scope.user_state, help="The hosts ip address or name")
    ssh_user = String(default='', scope=Scope.user_state, help="The username for ssh connection")
    ssh_pass = String(default='', scope=Scope.user_state, help="The password for ssh connection")
    ssh_port = Integer(default=22, scope=Scope.user_state, help="The port for ssh connection")
    ssh_pwd = String(default='~', scope=Scope.user_state, help="With cd command the path you were before is stored here")
    ssh_hostnames = List(scope=Scope.settings ,help="Editable property for studio version,defining machines to connect to.Field format :[hostname1,hostname2,...]")
    ssh_portList = List(scope=Scope.settings ,help="Editable property for studio version,defining port to connect to.Field format :[hostname1-Port,hostname2-port,...]")
    ssh_profiles = Dict(scope=Scope.settings ,help="Editable property for studio version,defining login profiles for machines.Field format :[Hostname1:[[user1,pass1],[user2,pass2]],Hostname2:[[user1,pass2],[user2,pass2]]]")
The first five variables should be Scope.user_state  because they are different for each user and based on user input
and the three next settings  because they are only defined by the teacher-instructor for all students

Alternatively insted of settings they could be content(more like global for more blocks )

I will commit the change soon.
Thank you for your feedback

**Comment by mirobillis** [comment]
fixed with commit   18bb984 on 21 April 2016
